# Generated by Django 6.0.6 on 2026-09-24 04:06

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.CharField(default=tasks.models.generar_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('target_date', models.DateField()),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Ejecutada', 'Ejecutada'), ('Pospuesta', 'Pospuesta')], default='Pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'subtasks',
                'managed': False,
            },
        ),
    ]
